export const initialMedicamentos = [
  {
    id: '1',
    name: 'Losartana',
    dosage: '50mg',
    frequency: '1x/dia',
    indication: 'Hipertensão arterial',
    notes: null,
  },
  {
    id: '2',
    name: 'Metformina',
    dosage: '850mg',
    frequency: '2x/dia',
    indication: 'Diabetes tipo 2',
    notes: 'Tomar após as refeições.',
  },
  {
    id: '3',
    name: 'Levotiroxina',
    dosage: '100mcg',
    frequency: '1x/dia',
    indication: 'Hipotireoidismo',
    notes: 'Tomar em jejum.',
  },
  {
    id: '4',
    name: 'Salbutamol',
    dosage: 'Inalatório',
    frequency: 'Uso em crises',
    indication: 'Asma',
    notes: 'Usar apenas em caso de dificuldade respiratória.',
  },
  {
    id: '5',
    name: 'Paracetamol',
    dosage: '500mg',
    frequency: 'A cada 6 horas',
    indication: 'Dor e febre',
    notes: 'Não exceder 4 doses diárias.',
  },
  {
    id: '6',
    name: 'Aspirina',
    dosage: '100mg',
    frequency: '1x/dia',
    indication: 'Prevenção de infarto',
    notes: 'Tomar com alimento para evitar irritação estomacal.',
  },
  {
    id: '7',
    name: 'Amoxicilina',
    dosage: '500mg',
    frequency: 'A cada 8 horas',
    indication: 'Infecções bacterianas',
    notes: 'Completar o ciclo de 7 dias, mesmo que os sintomas desapareçam.',
  },
  {
    id: '8',
    name: 'Ibuprofeno',
    dosage: '200mg',
    frequency: 'A cada 4-6 horas',
    indication: 'Dor e inflamação',
    notes: 'Evitar em pacientes com histórico de úlceras gástricas.',
  },
  {
    id: '9',
    name: 'Omeprazol',
    dosage: '20mg',
    frequency: '1x/dia',
    indication: 'Refluxo gástrico e úlceras',
    notes: 'Tomar antes do café da manhã.',
  },
  {
    id: '10',
    name: 'Dipirona',
    dosage: '1g',
    frequency: 'A cada 6-8 horas',
    indication: 'Dor e febre',
    notes: 'Não usar por mais de 5 dias consecutivos.',
  },
];
