export const initialPatients = [
    {
        id: '1',
        name: 'Maria Brito Maciel',
        lastConsultation: '15/03/2024',
        diagnosis: 'Hipertensão arterial, diabetes mellitus tipo 2',
        treatments: 'Losartana 50mg 1x/dia, Metformina 850mg 2x/dia',
        nextSteps: 'Retorno em 3 meses para acompanhamento.',
        allergies: null,
        isFavorite: true,
    },
    {
        id: '2',
        name: 'Maria Joaquina',
        lastConsultation: '22/02/2024',
        diagnosis: 'Asma brônquica',
        treatments: 'Salbutamol para crises, Corticoide inalatório contínuo',
        nextSteps: 'Espirometria em 1 mês.',
        allergies: 'Penicilina',
        isFavorite: false,
    },
    {
        id: '3',
        name: 'Carlos Henrique',
        lastConsultation: '10/01/2024',
        diagnosis: 'Obesidade grau 2',
        treatments: 'Mudança de estilo de vida, acompanhamento nutricional',
        nextSteps: 'Avaliação em 6 meses.',
        allergies: null,
        isFavorite: false,
    },
    {
        id: '4',
        name: 'Ana Beatriz',
        lastConsultation: '05/02/2024',
        diagnosis: 'Hipotireoidismo',
        treatments: 'Levotiroxina 100mcg/dia',
        nextSteps: 'Acompanhamento anual.',
        allergies: 'Lactose',
        isFavorite: true,
    },
];
